name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2. Bạn NHỚ PHẢI THÊM working-directory trỏ vào đúng thư mục bài 10 nhé 
      # (Giả sử bạn đặt tên thư mục là Bai10)
      - name: Build with Maven
        working-directory: ./Bai10
        run: mvn package
